name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DISPLAY: ':99.0'
    strategy:
      matrix:
        python-version: [3.9]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .
          pip install pytest

      - name: Set Python path for module resolution
        run: |
          export PYTHONPATH=$(pwd)/src:$PYTHONPATH

      - name: Run tests (Utilities)
        run: |
          pytest -v src/tihi/tests/test_baseline_correction.py
          pytest -v src/tihi/tests/test_distributions.py
          pytest -v src/tihi/tests/test_interpolate.py
          pytest -v src/tihi/tests/test_peaks.py
